/*
 * generated by Xtext 2.25.0
 */
package org.tracesec.graph.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GraphConfigurationUiModule extends AbstractGraphConfigurationUiModule {

	public GraphConfigurationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
