/*
 * generated by Xtext 2.26.0
 */
package org.tracesec.graph.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGraphConfigurationValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage.eINSTANCE);
		return result;
	}
}
