/*
 * generated by Xtext 2.25.0
 */
package org.tracesec.graph.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGraphConfigurationScopeProvider extends DelegatingScopeProvider {
}
