/*
 * generated by Xtext 2.25.0
 */
package org.tracesec.graph.dsl.validation;

import org.eclipse.xtext.validation.Check;
import org.tracesec.graph.dsl.graphConfiguration.Edge;
import org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class GraphConfigurationValidator extends AbstractGraphConfigurationValidator {

	@Check
	public void checkGreetingStartsWithCapital(final Edge reference) {
		final var type = reference.getReference().getEReferenceType();
		final var referencedType = reference.getType();
		if ((type != null) && (referencedType != null) && !type.isSuperTypeOf(referencedType)) {
			error("The reference is not in the type!",
					GraphConfigurationPackage.Literals.EDGE__TARGET);
		}
	}

}
