/**
 * generated by Xtext 2.26.0
 */
package org.tracesec.graph.dsl.graphConfiguration;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationFactory
 * @model kind="package"
 * @generated
 */
public interface GraphConfigurationPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "graphConfiguration";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.tracesec.org/graph/dsl/GraphConfiguration";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "graphConfiguration";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GraphConfigurationPackage eINSTANCE = org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl.init();

  /**
   * The meta object id for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.ConfigurationImpl <em>Configuration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.ConfigurationImpl
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getConfiguration()
   * @generated
   */
  int CONFIGURATION = 0;

  /**
   * The feature id for the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__DEFAULT = 0;

  /**
   * The feature id for the '<em><b>Consider</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__CONSIDER = 1;

  /**
   * The feature id for the '<em><b>Namespaces</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__NAMESPACES = 2;

  /**
   * The number of structural features of the '<em>Configuration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.NamespaceImpl <em>Namespace</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.NamespaceImpl
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getNamespace()
   * @generated
   */
  int NAMESPACE = 1;

  /**
   * The feature id for the '<em><b>Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMESPACE__PACKAGE = 0;

  /**
   * The feature id for the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMESPACE__DEFAULT = 1;

  /**
   * The feature id for the '<em><b>Consider</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMESPACE__CONSIDER = 2;

  /**
   * The feature id for the '<em><b>Include</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMESPACE__INCLUDE = 3;

  /**
   * The feature id for the '<em><b>Exclude</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMESPACE__EXCLUDE = 4;

  /**
   * The number of structural features of the '<em>Namespace</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMESPACE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.TypeImpl
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getType()
   * @generated
   */
  int TYPE = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__TYPE = 0;

  /**
   * The feature id for the '<em><b>Consider</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__CONSIDER = 1;

  /**
   * The feature id for the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__DEFAULT = 2;

  /**
   * The feature id for the '<em><b>Inlcude</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__INLCUDE = 3;

  /**
   * The feature id for the '<em><b>Exclude</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__EXCLUDE = 4;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.EdgeImpl <em>Edge</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.EdgeImpl
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getEdge()
   * @generated
   */
  int EDGE = 3;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE__REFERENCE = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE__TYPE = 1;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE__TARGET = 2;

  /**
   * The feature id for the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE__DIRECTION = 3;

  /**
   * The feature id for the '<em><b>Weight</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE__WEIGHT = 4;

  /**
   * The number of structural features of the '<em>Edge</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.WeightImpl <em>Weight</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.WeightImpl
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getWeight()
   * @generated
   */
  int WEIGHT = 4;

  /**
   * The number of structural features of the '<em>Weight</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEIGHT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.NumberWeightImpl <em>Number Weight</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.NumberWeightImpl
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getNumberWeight()
   * @generated
   */
  int NUMBER_WEIGHT = 5;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_WEIGHT__VALUE = WEIGHT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number Weight</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_WEIGHT_FEATURE_COUNT = WEIGHT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.AttributeWeightImpl <em>Attribute Weight</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.AttributeWeightImpl
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getAttributeWeight()
   * @generated
   */
  int ATTRIBUTE_WEIGHT = 6;

  /**
   * The feature id for the '<em><b>Owner</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_WEIGHT__OWNER = WEIGHT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_WEIGHT__VALUE = WEIGHT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Attribute Weight</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_WEIGHT_FEATURE_COUNT = WEIGHT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.tracesec.graph.dsl.graphConfiguration.Owner <em>Owner</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.tracesec.graph.dsl.graphConfiguration.Owner
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getOwner()
   * @generated
   */
  int OWNER = 7;

  /**
   * The meta object id for the '{@link org.tracesec.graph.dsl.graphConfiguration.Consider <em>Consider</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.tracesec.graph.dsl.graphConfiguration.Consider
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getConsider()
   * @generated
   */
  int CONSIDER = 8;

  /**
   * The meta object id for the '{@link org.tracesec.graph.dsl.graphConfiguration.Direction <em>Direction</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.tracesec.graph.dsl.graphConfiguration.Direction
   * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getDirection()
   * @generated
   */
  int DIRECTION = 9;


  /**
   * Returns the meta object for class '{@link org.tracesec.graph.dsl.graphConfiguration.Configuration <em>Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Configuration</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Configuration
   * @generated
   */
  EClass getConfiguration();

  /**
   * Returns the meta object for the attribute '{@link org.tracesec.graph.dsl.graphConfiguration.Configuration#getDefault <em>Default</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Default</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Configuration#getDefault()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Default();

  /**
   * Returns the meta object for the attribute '{@link org.tracesec.graph.dsl.graphConfiguration.Configuration#getConsider <em>Consider</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Consider</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Configuration#getConsider()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Consider();

  /**
   * Returns the meta object for the containment reference list '{@link org.tracesec.graph.dsl.graphConfiguration.Configuration#getNamespaces <em>Namespaces</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Namespaces</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Configuration#getNamespaces()
   * @see #getConfiguration()
   * @generated
   */
  EReference getConfiguration_Namespaces();

  /**
   * Returns the meta object for class '{@link org.tracesec.graph.dsl.graphConfiguration.Namespace <em>Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Namespace</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Namespace
   * @generated
   */
  EClass getNamespace();

  /**
   * Returns the meta object for the attribute '{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getPackage <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Package</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Namespace#getPackage()
   * @see #getNamespace()
   * @generated
   */
  EAttribute getNamespace_Package();

  /**
   * Returns the meta object for the attribute '{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getDefault <em>Default</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Default</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Namespace#getDefault()
   * @see #getNamespace()
   * @generated
   */
  EAttribute getNamespace_Default();

  /**
   * Returns the meta object for the attribute '{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getConsider <em>Consider</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Consider</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Namespace#getConsider()
   * @see #getNamespace()
   * @generated
   */
  EAttribute getNamespace_Consider();

  /**
   * Returns the meta object for the containment reference list '{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getInclude <em>Include</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Include</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Namespace#getInclude()
   * @see #getNamespace()
   * @generated
   */
  EReference getNamespace_Include();

  /**
   * Returns the meta object for the reference list '{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getExclude <em>Exclude</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Exclude</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Namespace#getExclude()
   * @see #getNamespace()
   * @generated
   */
  EReference getNamespace_Exclude();

  /**
   * Returns the meta object for class '{@link org.tracesec.graph.dsl.graphConfiguration.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the reference '{@link org.tracesec.graph.dsl.graphConfiguration.Type#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Type#getType()
   * @see #getType()
   * @generated
   */
  EReference getType_Type();

  /**
   * Returns the meta object for the attribute '{@link org.tracesec.graph.dsl.graphConfiguration.Type#getConsider <em>Consider</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Consider</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Type#getConsider()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Consider();

  /**
   * Returns the meta object for the attribute '{@link org.tracesec.graph.dsl.graphConfiguration.Type#getDefault <em>Default</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Default</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Type#getDefault()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Default();

  /**
   * Returns the meta object for the containment reference list '{@link org.tracesec.graph.dsl.graphConfiguration.Type#getInlcude <em>Inlcude</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inlcude</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Type#getInlcude()
   * @see #getType()
   * @generated
   */
  EReference getType_Inlcude();

  /**
   * Returns the meta object for the reference list '{@link org.tracesec.graph.dsl.graphConfiguration.Type#getExclude <em>Exclude</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Exclude</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Type#getExclude()
   * @see #getType()
   * @generated
   */
  EReference getType_Exclude();

  /**
   * Returns the meta object for class '{@link org.tracesec.graph.dsl.graphConfiguration.Edge <em>Edge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Edge</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Edge
   * @generated
   */
  EClass getEdge();

  /**
   * Returns the meta object for the reference '{@link org.tracesec.graph.dsl.graphConfiguration.Edge#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Reference</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Edge#getReference()
   * @see #getEdge()
   * @generated
   */
  EReference getEdge_Reference();

  /**
   * Returns the meta object for the reference '{@link org.tracesec.graph.dsl.graphConfiguration.Edge#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Edge#getType()
   * @see #getEdge()
   * @generated
   */
  EReference getEdge_Type();

  /**
   * Returns the meta object for the reference '{@link org.tracesec.graph.dsl.graphConfiguration.Edge#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Edge#getTarget()
   * @see #getEdge()
   * @generated
   */
  EReference getEdge_Target();

  /**
   * Returns the meta object for the attribute '{@link org.tracesec.graph.dsl.graphConfiguration.Edge#getDirection <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Direction</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Edge#getDirection()
   * @see #getEdge()
   * @generated
   */
  EAttribute getEdge_Direction();

  /**
   * Returns the meta object for the containment reference '{@link org.tracesec.graph.dsl.graphConfiguration.Edge#getWeight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Weight</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Edge#getWeight()
   * @see #getEdge()
   * @generated
   */
  EReference getEdge_Weight();

  /**
   * Returns the meta object for class '{@link org.tracesec.graph.dsl.graphConfiguration.Weight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Weight</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Weight
   * @generated
   */
  EClass getWeight();

  /**
   * Returns the meta object for class '{@link org.tracesec.graph.dsl.graphConfiguration.NumberWeight <em>Number Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Weight</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.NumberWeight
   * @generated
   */
  EClass getNumberWeight();

  /**
   * Returns the meta object for the attribute '{@link org.tracesec.graph.dsl.graphConfiguration.NumberWeight#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.NumberWeight#getValue()
   * @see #getNumberWeight()
   * @generated
   */
  EAttribute getNumberWeight_Value();

  /**
   * Returns the meta object for class '{@link org.tracesec.graph.dsl.graphConfiguration.AttributeWeight <em>Attribute Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Weight</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.AttributeWeight
   * @generated
   */
  EClass getAttributeWeight();

  /**
   * Returns the meta object for the attribute '{@link org.tracesec.graph.dsl.graphConfiguration.AttributeWeight#getOwner <em>Owner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Owner</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.AttributeWeight#getOwner()
   * @see #getAttributeWeight()
   * @generated
   */
  EAttribute getAttributeWeight_Owner();

  /**
   * Returns the meta object for the reference '{@link org.tracesec.graph.dsl.graphConfiguration.AttributeWeight#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Value</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.AttributeWeight#getValue()
   * @see #getAttributeWeight()
   * @generated
   */
  EReference getAttributeWeight_Value();

  /**
   * Returns the meta object for enum '{@link org.tracesec.graph.dsl.graphConfiguration.Owner <em>Owner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Owner</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Owner
   * @generated
   */
  EEnum getOwner();

  /**
   * Returns the meta object for enum '{@link org.tracesec.graph.dsl.graphConfiguration.Consider <em>Consider</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Consider</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Consider
   * @generated
   */
  EEnum getConsider();

  /**
   * Returns the meta object for enum '{@link org.tracesec.graph.dsl.graphConfiguration.Direction <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Direction</em>'.
   * @see org.tracesec.graph.dsl.graphConfiguration.Direction
   * @generated
   */
  EEnum getDirection();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GraphConfigurationFactory getGraphConfigurationFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.ConfigurationImpl <em>Configuration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.ConfigurationImpl
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getConfiguration()
     * @generated
     */
    EClass CONFIGURATION = eINSTANCE.getConfiguration();

    /**
     * The meta object literal for the '<em><b>Default</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__DEFAULT = eINSTANCE.getConfiguration_Default();

    /**
     * The meta object literal for the '<em><b>Consider</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__CONSIDER = eINSTANCE.getConfiguration_Consider();

    /**
     * The meta object literal for the '<em><b>Namespaces</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATION__NAMESPACES = eINSTANCE.getConfiguration_Namespaces();

    /**
     * The meta object literal for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.NamespaceImpl <em>Namespace</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.NamespaceImpl
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getNamespace()
     * @generated
     */
    EClass NAMESPACE = eINSTANCE.getNamespace();

    /**
     * The meta object literal for the '<em><b>Package</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAMESPACE__PACKAGE = eINSTANCE.getNamespace_Package();

    /**
     * The meta object literal for the '<em><b>Default</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAMESPACE__DEFAULT = eINSTANCE.getNamespace_Default();

    /**
     * The meta object literal for the '<em><b>Consider</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAMESPACE__CONSIDER = eINSTANCE.getNamespace_Consider();

    /**
     * The meta object literal for the '<em><b>Include</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAMESPACE__INCLUDE = eINSTANCE.getNamespace_Include();

    /**
     * The meta object literal for the '<em><b>Exclude</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAMESPACE__EXCLUDE = eINSTANCE.getNamespace_Exclude();

    /**
     * The meta object literal for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.TypeImpl
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__TYPE = eINSTANCE.getType_Type();

    /**
     * The meta object literal for the '<em><b>Consider</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__CONSIDER = eINSTANCE.getType_Consider();

    /**
     * The meta object literal for the '<em><b>Default</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__DEFAULT = eINSTANCE.getType_Default();

    /**
     * The meta object literal for the '<em><b>Inlcude</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__INLCUDE = eINSTANCE.getType_Inlcude();

    /**
     * The meta object literal for the '<em><b>Exclude</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__EXCLUDE = eINSTANCE.getType_Exclude();

    /**
     * The meta object literal for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.EdgeImpl <em>Edge</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.EdgeImpl
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getEdge()
     * @generated
     */
    EClass EDGE = eINSTANCE.getEdge();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDGE__REFERENCE = eINSTANCE.getEdge_Reference();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDGE__TYPE = eINSTANCE.getEdge_Type();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDGE__TARGET = eINSTANCE.getEdge_Target();

    /**
     * The meta object literal for the '<em><b>Direction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EDGE__DIRECTION = eINSTANCE.getEdge_Direction();

    /**
     * The meta object literal for the '<em><b>Weight</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDGE__WEIGHT = eINSTANCE.getEdge_Weight();

    /**
     * The meta object literal for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.WeightImpl <em>Weight</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.WeightImpl
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getWeight()
     * @generated
     */
    EClass WEIGHT = eINSTANCE.getWeight();

    /**
     * The meta object literal for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.NumberWeightImpl <em>Number Weight</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.NumberWeightImpl
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getNumberWeight()
     * @generated
     */
    EClass NUMBER_WEIGHT = eINSTANCE.getNumberWeight();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_WEIGHT__VALUE = eINSTANCE.getNumberWeight_Value();

    /**
     * The meta object literal for the '{@link org.tracesec.graph.dsl.graphConfiguration.impl.AttributeWeightImpl <em>Attribute Weight</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.AttributeWeightImpl
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getAttributeWeight()
     * @generated
     */
    EClass ATTRIBUTE_WEIGHT = eINSTANCE.getAttributeWeight();

    /**
     * The meta object literal for the '<em><b>Owner</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_WEIGHT__OWNER = eINSTANCE.getAttributeWeight_Owner();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_WEIGHT__VALUE = eINSTANCE.getAttributeWeight_Value();

    /**
     * The meta object literal for the '{@link org.tracesec.graph.dsl.graphConfiguration.Owner <em>Owner</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.tracesec.graph.dsl.graphConfiguration.Owner
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getOwner()
     * @generated
     */
    EEnum OWNER = eINSTANCE.getOwner();

    /**
     * The meta object literal for the '{@link org.tracesec.graph.dsl.graphConfiguration.Consider <em>Consider</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.tracesec.graph.dsl.graphConfiguration.Consider
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getConsider()
     * @generated
     */
    EEnum CONSIDER = eINSTANCE.getConsider();

    /**
     * The meta object literal for the '{@link org.tracesec.graph.dsl.graphConfiguration.Direction <em>Direction</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.tracesec.graph.dsl.graphConfiguration.Direction
     * @see org.tracesec.graph.dsl.graphConfiguration.impl.GraphConfigurationPackageImpl#getDirection()
     * @generated
     */
    EEnum DIRECTION = eINSTANCE.getDirection();

  }

} //GraphConfigurationPackage
