/**
 * generated by Xtext 2.25.0
 */
package org.tracesec.graph.dsl.graphConfiguration;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Namespace</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getPackage <em>Package</em>}</li>
 *   <li>{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getDefault <em>Default</em>}</li>
 *   <li>{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getConsider <em>Consider</em>}</li>
 *   <li>{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getInclude <em>Include</em>}</li>
 *   <li>{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getExclude <em>Exclude</em>}</li>
 * </ul>
 *
 * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getNamespace()
 * @model
 * @generated
 */
public interface Namespace extends EObject
{
  /**
   * Returns the value of the '<em><b>Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Package</em>' attribute.
   * @see #setPackage(String)
   * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getNamespace_Package()
   * @model
   * @generated
   */
  String getPackage();

  /**
   * Sets the value of the '{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getPackage <em>Package</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Package</em>' attribute.
   * @see #getPackage()
   * @generated
   */
  void setPackage(String value);

  /**
   * Returns the value of the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default</em>' attribute.
   * @see #setDefault(int)
   * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getNamespace_Default()
   * @model
   * @generated
   */
  int getDefault();

  /**
   * Sets the value of the '{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getDefault <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default</em>' attribute.
   * @see #getDefault()
   * @generated
   */
  void setDefault(int value);

  /**
   * Returns the value of the '<em><b>Consider</b></em>' attribute.
   * The literals are from the enumeration {@link org.tracesec.graph.dsl.graphConfiguration.Consider}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consider</em>' attribute.
   * @see org.tracesec.graph.dsl.graphConfiguration.Consider
   * @see #setConsider(Consider)
   * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getNamespace_Consider()
   * @model
   * @generated
   */
  Consider getConsider();

  /**
   * Sets the value of the '{@link org.tracesec.graph.dsl.graphConfiguration.Namespace#getConsider <em>Consider</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Consider</em>' attribute.
   * @see org.tracesec.graph.dsl.graphConfiguration.Consider
   * @see #getConsider()
   * @generated
   */
  void setConsider(Consider value);

  /**
   * Returns the value of the '<em><b>Include</b></em>' containment reference list.
   * The list contents are of type {@link org.tracesec.graph.dsl.graphConfiguration.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Include</em>' containment reference list.
   * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getNamespace_Include()
   * @model containment="true"
   * @generated
   */
  EList<Type> getInclude();

  /**
   * Returns the value of the '<em><b>Exclude</b></em>' reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EClass}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exclude</em>' reference list.
   * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getNamespace_Exclude()
   * @model
   * @generated
   */
  EList<EClass> getExclude();

} // Namespace
