/**
 * generated by Xtext 2.26.0
 */
package org.tracesec.graph.dsl.graphConfiguration;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Number Weight</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.tracesec.graph.dsl.graphConfiguration.NumberWeight#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getNumberWeight()
 * @model
 * @generated
 */
public interface NumberWeight extends Weight
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getNumberWeight_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link org.tracesec.graph.dsl.graphConfiguration.NumberWeight#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // NumberWeight
