/**
 * generated by Xtext 2.34.0
 */
package org.tracesec.graph.dsl.graphConfiguration;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.tracesec.graph.dsl.graphConfiguration.Type#getType <em>Type</em>}</li>
 *   <li>{@link org.tracesec.graph.dsl.graphConfiguration.Type#getConsider <em>Consider</em>}</li>
 *   <li>{@link org.tracesec.graph.dsl.graphConfiguration.Type#getDefault <em>Default</em>}</li>
 *   <li>{@link org.tracesec.graph.dsl.graphConfiguration.Type#getInlcude <em>Inlcude</em>}</li>
 *   <li>{@link org.tracesec.graph.dsl.graphConfiguration.Type#getExclude <em>Exclude</em>}</li>
 * </ul>
 *
 * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(EClass)
   * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getType_Type()
   * @model
   * @generated
   */
  EClass getType();

  /**
   * Sets the value of the '{@link org.tracesec.graph.dsl.graphConfiguration.Type#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(EClass value);

  /**
   * Returns the value of the '<em><b>Consider</b></em>' attribute.
   * The literals are from the enumeration {@link org.tracesec.graph.dsl.graphConfiguration.Consider}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consider</em>' attribute.
   * @see org.tracesec.graph.dsl.graphConfiguration.Consider
   * @see #setConsider(Consider)
   * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getType_Consider()
   * @model
   * @generated
   */
  Consider getConsider();

  /**
   * Sets the value of the '{@link org.tracesec.graph.dsl.graphConfiguration.Type#getConsider <em>Consider</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Consider</em>' attribute.
   * @see org.tracesec.graph.dsl.graphConfiguration.Consider
   * @see #getConsider()
   * @generated
   */
  void setConsider(Consider value);

  /**
   * Returns the value of the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default</em>' attribute.
   * @see #setDefault(int)
   * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getType_Default()
   * @model
   * @generated
   */
  int getDefault();

  /**
   * Sets the value of the '{@link org.tracesec.graph.dsl.graphConfiguration.Type#getDefault <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default</em>' attribute.
   * @see #getDefault()
   * @generated
   */
  void setDefault(int value);

  /**
   * Returns the value of the '<em><b>Inlcude</b></em>' containment reference list.
   * The list contents are of type {@link org.tracesec.graph.dsl.graphConfiguration.Edge}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inlcude</em>' containment reference list.
   * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getType_Inlcude()
   * @model containment="true"
   * @generated
   */
  EList<Edge> getInlcude();

  /**
   * Returns the value of the '<em><b>Exclude</b></em>' reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EReference}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exclude</em>' reference list.
   * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getType_Exclude()
   * @model
   * @generated
   */
  EList<EReference> getExclude();

} // Type
