/**
 * generated by Xtext 2.34.0
 */
package org.tracesec.graph.dsl.graphConfiguration;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Weight</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.tracesec.graph.dsl.graphConfiguration.GraphConfigurationPackage#getWeight()
 * @model
 * @generated
 */
public interface Weight extends EObject
{
} // Weight
