<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qualitymodel" nsURI="http://www.tracesec.org/qualitymodel" nsPrefix="org.tracesec.qualitymodel">
  <eClassifiers xsi:type="ecore:EClass" name="QualityModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualities" upperBound="-1"
        eType="#//Quality" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Quality"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quality">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspects" upperBound="-1"
        eType="#//Aspect" containment="true" eOpposite="#//Aspect/owner"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relevantElements" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aspect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="#//Priority"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quality" eType="#//Quality"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Quality"
        eOpposite="#//Quality/aspects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Priority">
    <eLiterals name="LOW" value="25"/>
    <eLiterals name="MEDIUM" value="50"/>
    <eLiterals name="HIGH" value="75"/>
    <eLiterals name="ESSENTIAL" value="100"/>
  </eClassifiers>
</ecore:EPackage>
