/*
 * generated by Xtext 2.25.0
 */
package org.tracesec.graph.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.tracesec.graph.dsl.GraphConfigurationRuntimeModule;
import org.tracesec.graph.dsl.GraphConfigurationStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GraphConfigurationIdeSetup extends GraphConfigurationStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GraphConfigurationRuntimeModule(), new GraphConfigurationIdeModule()));
	}
	
}
