/*
 * generated by Xtext 2.25.0
 */
package org.tracesec.graph.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class GraphConfigurationIdeModule extends AbstractGraphConfigurationIdeModule {
}
