/*
 * generated by Xtext 2.26.0
 */
package org.tracesec.graph.dsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.tracesec.graph.dsl.services.GraphConfigurationGrammarAccess;

@SuppressWarnings("all")
public class GraphConfigurationSyntacticSequencer extends AbstractSyntacticSequencer {

	protected GraphConfigurationGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Namespace___IncludeKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (GraphConfigurationGrammarAccess) access;
		match_Namespace___IncludeKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getNamespaceAccess().getIncludeKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getNamespaceAccess().getLeftCurlyBracketKeyword_5_1()), new TokenAlias(false, false, grammarAccess.getNamespaceAccess().getRightCurlyBracketKeyword_5_3()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Namespace___IncludeKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q.equals(syntax))
				emit_Namespace___IncludeKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('include' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     consider=Consider (ambiguity) 'exclude' '{' exclude+=[EClass|ID]
	 *     consider=Consider (ambiguity) '}' (rule end)
	 *     default=INT (ambiguity) 'exclude' '{' exclude+=[EClass|ID]
	 *     default=INT (ambiguity) '}' (rule end)
	 *     package=STRING '{' (ambiguity) 'exclude' '{' exclude+=[EClass|ID]
	 *     package=STRING '{' (ambiguity) '}' (rule end)
	 
	 * </pre>
	 */
	protected void emit_Namespace___IncludeKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
