/*
 * generated by Xtext 2.34.0
 */
package org.tracesec.graph.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.tracesec.graph.dsl.parser.antlr.internal.InternalGraphConfigurationParser;
import org.tracesec.graph.dsl.services.GraphConfigurationGrammarAccess;

public class GraphConfigurationParser extends AbstractAntlrParser {

	@Inject
	private GraphConfigurationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGraphConfigurationParser createParser(XtextTokenStream stream) {
		return new InternalGraphConfigurationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Configuration";
	}

	public GraphConfigurationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GraphConfigurationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
