/*
 * generated by Xtext 2.25.0
 */
package org.tracesec.graph.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GraphConfigurationStandaloneSetup extends GraphConfigurationStandaloneSetupGenerated {

	public static void doSetup() {
		new GraphConfigurationStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
